[#24713] docdb: PG Integration with the DocDB advisory lock functionality
Summary:
This diff adds PG integration with the DocDB advisory lock functionality.
Only transaction level locks are supported.

When PG flag `ysql_yb_enable_advisory_lock` has been set to true, user can use transaction level advisory locks.
```
void pg_advisory_xact_lock(key bigint)
void pg_advisory_xact_lock(key1 int, key2 int)
void pg_advisory_xact_lock_shared(key bigint)
void pg_advisory_xact_lock_shared(key1 int, key2 int)
boolean pg_try_advisory_xact_lock(key bigint)
boolean pg_try_advisory_xact_lock(key1 int, key2 int)
boolean pg_try_advisory_xact_lock_shared(key bigint)
boolean pg_try_advisory_xact_lock_shared(key1 int, key2 int)

```

If session level advisory lock functions are called, it will raise an error from pg_client_session layer.
```
ERROR: session-level advisory locks are not yet implemented
```

**Upgrade/Rollback safety:**
The advisory lock feature is guarded by ysql_yb_enable_advisory_lock (false by default).

Test Plan:
advisory_lock-test
pg_advisory_lock-test

Reviewers: pjain, hsunder, bkolagani, yyan

Reviewed By: bkolagani

Subscribers: ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D40617